### ISSUE TITLE
Create proper PIP source distribution

### ISSUE THREAD

**Issue by davidinouye** [davidinouye/destructive-deep-learning#21]
Ideally we would generate both a source distribution and a wheel distribution that is precompiled... though not sure if that is possible.

**Comment by davidinouye** [comment]
Create source distribution and bdist_wheel:
```
python setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
```

Install attempt
```
conda create -n ddl-test
source activate ddl-test
python -m pip install --verbose --index-url https://test.pypi.org/simple/ ddl
```

Error:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8w/5s40kmg936g4b_b77_26g0d40000gn/T/pip-build-m983kjmg/ddl/setup.py", line 76, in <module>
        setup(**metadata)
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/private/var/folders/8w/5s40kmg936g4b_b77_26g0d40000gn/T/pip-build-m983kjmg/ddl/setup.py", line 37, in configuration
        config.add_subpackage('ddl.externals.mlpack')
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 1029, in add_subpackage
        caller_level = 2)
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 998, in get_subpackage
        caller_level = caller_level + 1)
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "ddl/externals/mlpack/setup.py", line 94, in configuration
        config.ext_modules = cythonize(config.ext_modules)
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 908, in cythonize
        aliases=aliases)
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 778, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/dinouye/anaconda3/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 124, in nonempty
        raise ValueError(error_msg)
    ValueError: '_arma_numpy.pyx' doesn't match any files
    Downloading mlpack source
    Extracting tar.gz file
    Prepending flag for PIC
    Removing old build directory if necessary and creating new build directory
    Running cmake
    Exporting environment variables needed for cmake in Mac OS
    Building mlpack
    non-existing path in 'ddl/externals/mlpack': '_arma_numpy.pyx'
    non-existing path in 'ddl/externals/mlpack': '_det.pyx'
```

**Comment by davidinouye** [comment]
Create source distribution and bdist_wheel:
python setup.py sdist bdist_wheel

**Comment by davidinouye** [comment]
Probably need to edit a MANIFEST.in file

**Comment by davidinouye** [comment]
https://github.com/pypa/manylinux
Seems to be the way to do it for linux.

Here is how NumPy etc does their wheels:

https://github.com/MacPython/numpy-wheels

Background to the setup:

https://github.com/MacPython/wiki/wiki

https://github.com/matthew-brett/multibuild

Discussion thread: https://github.com/biopython/biopython/issues/1296

**Comment by davidinouye** [comment]
Creating wheels is much more involved so I split this into two issues, one for the source distribution and the other for a linux, windows and mac wheels (see issue #27).

**Comment by davidinouye** [comment]
I at least uploaded a new 0.0.2 version.
